import subprocess
from time import strftime
import requests
from fpdf import FPDF 
import datetime;
from openpyxl import Workbook
import openpyxl

global city, username
username=input("Enter Username: ")
cityinp=input("Enter City: ")

def makepdf(x,y,resultfromtxt):
    class PDF(FPDF):
        def header(self):
            self.image('pdfbgi.png', 0, 0, 210)
            self.set_font('Arial', 'B', 30)
            self.cell(80)
            self.cell(30, 30, 'Mal-Or-Not', 0, 1, 'C')
            self.set_font('Arial', 'U', 25)
            if(y=='ip' or y=='url'):
                self.cell(190, 10, y.upper()+' Report', 0, 1, 'C')
            else:
                self.cell(190, 10, y.capitalize()+' Report', 0, 1, 'C')
            self.ln(20)

        def footer(self):
            self.set_y(-20)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 5, "Report generated at: "+txs, 0, 1, 'L')
            self.cell(0, 5, "Report generated by: "+username, 0, 1, 'L')
            self.cell(0, 5, "Location: "+cityinp, 0, 0, 'L')
            self.cell(0, 5, 'Page ' + str(self.page_no()) + '/{nb}', 0, 1, 'R')
            self.set_text_color(127, 127, 127)
            self.cell(0, 5, "© 2022 Mal-Or-Not, All rights reserved.", 0, 0, 'C')

    pdf = PDF()
    pdf.alias_nb_pages()
    name="reports/"+y+"/"+x+".pdf"

    ct=datetime.datetime.now().isoformat(' ', 'seconds')
    txs=str(ct)

    pdf.add_page()
    pdf.set_font("Arial", 'B', size = 15) 
    file = open("output/"+y+"/"+x+"."+y+".report", "r") 
    for g in file:
            pdf.multi_cell(0, 10, txt = g, border=1, align = 'L') 

    pdf.output(name)

def masterxl(newinp, typeid, sheettype):
    txttoexcel = open("output/"+typeid+"/"+newinp+"."+typeid+".report", 'r')
    lst=[]
    newstr=""
    cnt=0
    for i in txttoexcel:
        x=i.split(':',1)
        if len(x) > 1:
            lst.append(x[1].strip())
        if (cnt>=9 and (typeid=="file" or typeid=="url")):
            newstr=newstr+"\n"+i
        cnt=cnt+1
    newstr=newstr.strip()
    if (not newstr):
        if typeid=="file":
            newstr=newstr+"This file is safe!"
        elif typeid=="url":
            newstr=newstr+"The URL is safe to use!"
    lst.append(newstr)
    lst = list(filter(None, lst))
    txttoexcel.close()

    book = openpyxl.load_workbook('masterexcel.xlsx')
    book.active = book[sheettype]
    sheet=book.active
    row1 = lst
    sheet.append(row1)
    book.save("masterexcel.xlsx")

def IP():
    global typeid
    typeid='ip'
    global inp
    inp= input("Enter IP: ")
    subprocess.check_output(["./ipintel.sh", "-i", inp])
    with open("output/ip/"+inp+".ip.report","r") as f:
        data=f.read()
    print ('RESULT BEGINS HERE'.center(100,'-'))
    print (data)
    print ('RESULT ENDS HERE'.center(100,'-'))
    makepdf(inp,typeid,data)
    masterxl(inp, typeid, 'IP')

def Domain():
    with open("usernamelocation.txt","w") as n:
        n.write(username+'\n'+cityinp)
    subprocess.call(['python3','WhoIsInfo.py'])

def Email():
    global typeid
    typeid='email'
    global inp
    inp= input("Enter E-MAIL: ")
    subprocess.check_output(["./email.sh",inp])
    with open("output/email/"+inp.split("@")[0]+".email.report","r") as f:
        data=f.read()
    print ('RESULT BEGINS HERE'.center(100,'-'))
    print (data)
    print ('RESULT ENDS HERE'.center(100,'-'))    
    newinp=inp.split("@")[0]
    makepdf(newinp,typeid,data)
    masterxl(newinp, typeid, 'E-mail')

def phno():
    global typeid
    typeid='number'
    global inp
    inp= input("Enter phone number: ")
    subprocess.check_output(["sh","./number.sh", inp])
    with open("output/number/"+inp+".number.report","r") as f:
        data=f.read()
    print ('RESULT BEGINS HERE'.center(100,'-'))
    print (data)
    print ('RESULT ENDS HERE'.center(100,'-'))
    makepdf(inp,typeid,data)
    masterxl(inp, typeid, 'Phone no.')

def link():
    global typeid
    typeid='url'
    global inp
    inp= input("Enter the URL: ")
    subprocess.check_output(["./urlreport.sh", inp])
    with open("output/url/"+inp.split("/")[2]+".url.report","r") as f:
        data=f.read()
    print ('RESULT BEGINS HERE'.center(100,'-'))
    print (data)
    print ('RESULT ENDS HERE'.center(100,'-'))
    newinp=inp.split("/")[2]
    makepdf(newinp,typeid,data)
    masterxl(newinp, typeid, 'URL')

def files():
    global typeid
    typeid='file'
    global inp
    inp = input("Enter file path: ")
    subprocess.check_output(["./file.sh", inp])
    with open("output/file/"+inp.split("/")[-1].split(".")[0]+".file.report","r") as f:
        data=f.read()
    print ('RESULT BEGINS HERE'.center(100,'-'))
    print (data)
    print ('RESULT ENDS HERE'.center(100,'-'))
    newinp=inp.split("/")[-1].split(".")[0]
    makepdf(newinp,typeid,data)
    masterxl(newinp, typeid, 'File')

while True:
    choice = int(input("\nWhich entity do you wish to test?\n1) FILE\n2) URL\n3) IP\n4) E-MAIL\n5) Domain\n6) Phone Number\n7) Exit\nEnter Choice: "))
    if choice==1:
            files()
    elif choice==2:
            link()
    elif choice==3:
            IP()
    elif choice==4:
            Email()
    elif choice==5:
            Domain()
    elif choice==6:
            phno()
    elif choice==7:
            print ("^_^ Thank you for using Mal-OR-Not! ^_^".center(100,'-'))
            break
    else:
            print ("Incorrect Option! The range is between 1-7. Pls try again.")
